[package]
name = "lazyc"
version = "0.4.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "4.1.4", features = ["derive"]}
colored = "2.0.0"
exitcode = "1.1.2"
json = "0.12.4"
